name: Lint

on:
  push:
    paths:
      - "BlenderAddOn/**"
      - ".github/workflows/lint.yml"
      - "ruff.toml"
  pull_request:
    paths:
      - "BlenderAddOn/**"
      - ".github/workflows/lint.yml"
      - "ruff.toml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3
        with:
          args: "check BlenderAddOn/binjo_addon"

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.2
        with:
          persona: pedantic
