name: Lint

on:
  push:
    paths:
      - "BlenderAddOn/**"
      - ".github/workflows/lint.yml"
      - "ruff.toml"
  pull_request:
    paths:
      - "BlenderAddOn/**"
      - ".github/workflows/lint.yml"
      - "ruff.toml"

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          args: "check BlenderAddOn/binjo_addon"

  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout the repository
      security-events: write # to upload SARIF results to the Security tab
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          persona: pedantic
